### ISSUE TITLE
Unrecognized option in openvpn config on ubuntu 16.04

### ISSUE THREAD

**Issue by ronnylov** [LetheanMovement/lethean-vpn#105]
Hi!

In the template 
https://github.com/LetheanMovement/lethean-vpn/blob/master/conf/openvpn_server.tmpl

Following option is not recognized by openvpn version 2.3.10 on ubuntu 16.04:
verify-client-cert none

This is preventing openvpn server to start.
Removing this line allowed the server to start. Is this line necessary?

https://community.openvpn.net/openvpn/wiki/DeprecatedOptions

**Comment by ronnylov** [comment]
Without this parameter I get TLS errors.
TLS_ERROR: BIO read tls_read_plaintext error: error:140890C7:SSL routines:ssl3_get_client_certificate:peer did not return a certificate

**Comment by limosek** [comment]
Yes, this parameter is necessary. It is not deprecated but your openvpn binary is old.
You can replace this line by --client-cert-not-required which is accepted settings for your version.
But we will probably not support older openvpn by native way.

**Comment by ronnylov** [comment]
I see. I am moving away to debian. But good to know if someone ask about ubuntu 16.04

**Comment by ronnylov** [comment]
Closing the issue. Solved by upgrade.
