### ISSUE TITLE
lthn-easy-deploy-node.sh error "dispatcher.ini already exists"

### ISSUE THREAD

**Issue by ronnylov** [LetheanMovement/lethean-vpn#111]
A clean debian 9 installation after installing packages lethean-vpn, lethean-wallet-cli and lethean-wallet-vpn-rpc. Rinning the lthn-easy-deploy-node.sh stops with following error:

"dispatcher.ini already exists! Stopping. To continue, remove old /etc/lthn/dispatcher.ini and run again by yourself!"

Manually removing dispatcher.ini makes it possible to run the script without this error.

**Comment by ronnylov** [comment]
This is the output of deploy script with new debian packages on fresh debian install.
Script was run with sudo.

```
Synchronizing state of haproxy.service with SysV service script with /lib/systemd/systemd-sysv-install.
Executing: /lib/systemd/systemd-sysv-install disable haproxy
Synchronizing state of openvpn.service with SysV service script with /lib/systemd/systemd-sysv-install.
Executing: /lib/systemd/systemd-sysv-install disable openvpn
Synchronizing state of tinyproxy.service with SysV service script with /lib/systemd/systemd-sysv-install.
Executing: /lib/systemd/systemd-sysv-install enable tinyproxy
dispatcher.ini already exists! Stopping. To continue, remove old /etc/lthn/dispatcher.ini and run again by yourself!
```
So the error is still there.

**Comment by limosek** [comment]
should be fixed in https://github.com/LetheanMovement/lethean-vpn/pull/107

**Comment by ronnylov** [comment]
I tested with debian package lethean-vpn 3.1.0-8 and confirm this issue is fixed. No such error anymore.
