### ISSUE TITLE
Stopping daemons in lthn-easy-deploy-node.sh does not work

### ISSUE THREAD

**Issue by ronnylov** [LetheanMovement/lethean-vpn#112]
haproxy.service is still running after executing lthn-easy-deploy-node as root. The part of the script that stop and disable haproxy.service and openvpn.service does not seem to work. Tinyproxy.service is running though.

Temporary fix: Stop and disable haproxy.service and openvpn.service manually

```
$ sudo systemctl stop haproxy.service
$ sudo systemctl disable haproxy.service
$ sudo systemctl stop openvpn.service
$ sudo systemctl disable openvpn.service
```

**Comment by limosek** [comment]
I would need some log here. Can you paste entire screen log of easy-deploy script please?
I cannot reproduce.

**Comment by ronnylov** [comment]
This was with previous version of debian packages. I Think you fixed it but here is the log.
[deploy.log](https://github.com/LetheanMovement/lethean-vpn/files/3309052/deploy.log)

**Comment by ronnylov** [comment]
I did not see this from log though. I noticed dameons were still running after deploy was executed. When I tested latest packages I saw from log that daemons were handled.

**Comment by ronnylov** [comment]
Tested with debian package lethean-vpn 3.1.0-8
I confirm that this issue is now fixed. These services are not running after executing deploy script.
