### ISSUE TITLE
Tinyproxy may have ipv6 issues. Fix in dispatcher.ini

### ISSUE THREAD

**Issue by ronnylov** [LetheanMovement/lethean-vpn#113]
If some webpages randomly not open when using tinyproxy with lethean-vpn you can try following fix. Change localhost to 127.0.0.1 in dispatcher.ini. This should also be default setting in dispatcher.ini

This line:
`backend_proxy_server=localhost:8888`

change it to this:
`backend_proxy_server=127.0.0.1:8888`

**Comment by limosek** [comment]
should be solved in https://github.com/LetheanMovement/lethean-vpn/pull/107/commits/0f5a9f0fd03a25bc35a0c71419176814c54a1f0b
Please test

**Comment by ronnylov** [comment]
Yes it is fixed in debian package lethean-vpn version 3.1.0-8
