### ISSUE TITLE
Change default tinyproxy.conf ConnectPort settings

### ISSUE THREAD

**Issue by ronnylov** [LetheanMovement/lethean-vpn#114]
By default tinyproxy.conf have ports 443 and 563. Port 563 is not necessary for web surfing. We could also add some more ports. I suggest following:

ConnectPort 80
ConnectPort 443
ConnectPort 5060
ConnectPort 8443

Port 80 is used for http.
5060 is used by speedtest.net
8443 is used by tradeogre.com

See full description [here](https://github.com/ronnylov/lethean-vpn/wiki/Full-Lethean-exit-node-install-guide#setup-tinyproxy)

**Comment by limosek** [comment]
Tinyproxy is just dependency of dispatcher. It has its own config and debian package.
It is not common to touch config of one debian package by another debian package.

easy-deploy can probably change these settings. But I am not sure it is good idea. When something will change in other package config, things can be broken.

**Comment by ronnylov** [comment]
OK it is probably not very important. Users can adjust if they need and basic web surfing works using https with default config of tinyproxy.

**Comment by limosek** [comment]
Should be fixed by https://github.com/LetheanMovement/lethean-vpn/pull/107
Added into easy-deploy script

**Comment by ronnylov** [comment]
Confirmed that it was fixed when testing debian package lethean-vpn 3.1.0-8
