### ISSUE TITLE
Editing exiting service config using dispatcher (-E) increment service Id !?

### ISSUE THREAD

**Issue by zib92130** [LetheanMovement/lethean-vpn#13]
Unless I'm mistaken, when you interactive edit existing config (**sdp.json**) with` itnsdispatcher -E`  (for example to change cost), the existing **service Id** is incremented in the saved (overwritten) config.
Take the default service with Id '1A'. After interactive change, dispatcher will not restart with that clue :
`WARNING:root:Unknown parameter reneg for service 1B`

Problem maybe lies in `sdp.py` , function editService (called from itnsdispatcher.py).
That call of `s.checkConfig(cap.CAP)` looks to pass "None" ServiceId leading to a new service Id creation within `setId()` ... instead of just setting `self.data['id']`

**Comment by limosek** [comment]
Thank you for reporting this!
Repaired now.

**Comment by zib92130** [comment]
FYI this is working on my own now.  Thx
