### ISSUE TITLE
Can't restart dispatcher after change "remove PIDfile after service stop"

### ISSUE THREAD

**Issue by zib92130** [LetheanMovement/lethean-vpn#16]
I've followed the new dispatcher update in the readme.
But at the last command (restart), there's an error :
```
$ sudo systemctl restart itnsdispatcher
Failed to restart itnsdispatcher.service: Unit itnsdispatcher.service is not loaded properly: Exec format error.
See system logs and 'systemctl status itnsdispatcher.service' for details.
```

Reverting back on the latest change on itnsdispatcher.service (ExecStopPost) and the restart works (doing the whole update, `not only sudo systemctl restart itnsdispatcher` .

**Comment by zib92130** [comment]
That's what I did (I follow the dispatcher update). I copy/paste this :
```
-------------------------------------
git pull
./configure.sh --easy
make install
rm -f /opt/itns/var/authids.db
sudo systemctl daemon-reload
sudo systemctl restart itnsdispatcher
-------------------------------------
```
I may be wrong somewhere... but I've checked I can reproduce, by add/removing the line ... strange.  Need to figure out where I'm wrong.

**Comment by limosek** [comment]
Not sure what happened there but it works for me with latest code. 
I think it was something with update process and maybe itnsdispatcher.service was not updated in system folder. Closing for now.
