### ISSUE TITLE
Client cannot CONNECT (NOPAYMENT error) because wrongly assumed "Not enough credit"

### ISSUE THREAD

**Issue by zib92130** [LetheanMovement/lethean-vpn#18]
Tried to connect on my own exit-node from another server (all Ubuntu 18).
Once payment sent, exit-node was waiting for 2 confirmations.
When it finally happened, **authid** linked with client was added to ACL. OK.

But according to logs the "Start spending" only triggered 30 seconds later, while some LTHN was spent since.
At the same second there were :
- Start spending
- Spent 0.012324, new balance 0.737676
- Not enough credit for authid   ...  need at least 0.75

So there was **not a single second of effective service** [but it was paid !] as the check for requested amount was done *AFTER* starting to decrement payment.
I understand this check is mandatory to respect the choice of the exit-node owner for the 1st pre-paid duration (AKA *NO* pro-rated duration based on what amount the client has sent).
Here that's clearly another problem of a wrong (shorter) session duration, as no service is offered !

Find the dispatcher log attached (check-out summary at the beginning)
[bug_exit_node_anonymized.log](https://github.com/LetheanMovement/lethean-vpn/files/2397910/bug_exit_node_anonymized.log)
Note the client's IP was anonymized to 12.34.56.78 ! ;-)

**Comment by ronnylov** [comment]
I have similar issue. My exit node is set up with 30 minutes 0 confirmations on first payment and then 60 minutes 1 confirmation on following payments.

It disconnects soon after connection.
This is shown:
```
INFO:root:Got payment for service 1a, auth=1A31675244105594, amount=1.5, confirmations=0, height=0, txid=00402eafa61cfd185814e09e23b1f586c817faec1ac14d08cc2e64a3c5fd9fa7
INFO:root:Not enough credit for authid 1A31675244105594 and service 1A (firstPrePaidMinutes=30, balance=1.4749570349852243), need at least 1.5
```
I wonder "got payment for service 1a" and then "Not enough credit ... service 1A"
I mean "1a" and "1A" is not the same.
I am pretty sure I have written "1A" in both dispatcher ini and sdp.json.

**Comment by limosek** [comment]
Thank you for reporting this. I already found this bug and trying to repair in https://github.com/LetheanMovement/lethean-vpn/tree/develop/limo/reworkSpending
You can even look at https://github.com/LetheanMovement/lethean-vpn/blob/develop/limo/reworkSpending/doc/timing.svg
I tried to create diagram let spending timing is accurate. It needs more documentation but it is kickoff version.

Do not forget you need devel version of BE to work with.

**Comment by ronnylov** [comment]
The latest release v3.0.0.b2 have fixed the initial payment error.
But now we got a similar problem at first subsequent payment.
All works well until end of first payment period but auto-renewal function does not work.

**Comment by limosek** [comment]
We are working on this. This has to be repaired on wallet side.

**Comment by limosek** [comment]
Resolved on dispatcher side by https://github.com/LetheanMovement/lethean-vpn/commit/4d9d62dbc1522fef308af19f92c937664d83de66
