### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by bit2017user** [LetheanMovement/lethean-vpn#21]
Is there a way for you to provide an Ubuntu ready for use just to configure the wallet ?

**Comment by valiant1x** [comment]
We would like to have a docker image established at some point in the future. In the meantime, have you tried following the [README](https://github.com/LetheanMovement/lethean-vpn/blob/master/README.md)? Can you clarify which point of the documentation is unclear?

**Comment by bit2017user** [comment]
Hi
I used the easy install but I don't understand where to configure the wallet and how to check and change the settings after.
Sorry

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by iedemam** [comment]
We're working on a more integrated delivery in the future but for now, this is what we have. If you have a specific question, please re-open the ticket and we can resolve individual issues.
