### ISSUE TITLE
Exit node and client BE cannot use same wallet

### ISSUE THREAD

**Issue by kosztyua** [LetheanMovement/lethean-vpn#23]
When using the same wallet for exit node and BE, the node never registers payments, client keeps waiting forever for node to accept connection. Not sure if anyone ever used this, but still a finding :)

Node and wallet version v3.0.0.b2

**Comment by limosek** [comment]
This is not possible from the theory of operation. There must be two separate wallets. 
We will update doc to mention this.

**Comment by kosztyua** [comment]
Thanks for looking into this!
