### ISSUE TITLE
Closing the browser interrupts the session to exit node

### ISSUE THREAD

**Issue by kosztyua** [LetheanMovement/lethean-vpn#24]
Closing and reopening the browser, while keeping the wallet running, will result in interrupted session and cannot reestablish connection with BE to node without first paying again. 

Node & wallet v3.0.0.b2, chrome 3.0.0 (1 October)

**Comment by limosek** [comment]
Unfortunately, we were not able to replicate this.  Can you be more specific and say more here?

**Comment by limosek** [comment]
We will close it now. If we have more information about your case, we can reopen later.

**Comment by kosztyua** [comment]
My assumption is that it has something to do with the instability of running the wallet in vmware, will try to experiment with it and post my results. Thanks for looking into this!
