### ISSUE TITLE
Lethean-wallet-vpn-rpc block version too high

### ISSUE THREAD

**Issue by northriptl** [LetheanMovement/lethean-vpn#38]
When i run lethean-wallet-vpn-rpc I get the following error after it idles for a few minutes. It initially runs fine with no errors, then gives the "block version too high" error a few times then exits. The wallet was generated with lethean-wallet-cli in the same download as the vpn-rpc file.

Changelog states version is v2.0.2.1 - 2018.05.10

Download is lethean-cli-linux-64bit-letheanize-e45d13b

I have attached the error as a text file
[lethean_wallet_cpn_rpc_error.txt](https://github.com/LetheanMovement/lethean-vpn/files/2516522/lethean_wallet_cpn_rpc_error.txt)

**Comment by kosztyua** [comment]
That version is ancient and we just had a hard fork a few days ago. Download the latest and use that: https://github.com/LetheanMovement/lethean/releases

/closed

**Comment by northriptl** [comment]
I will try that. Not sure why i was working with such an old version, i used git clone on the repo to download the code. Perhaps i used the wrong repo.

git clone https://github.com/LetheanMovement/lethean-vpn
