### ISSUE TITLE
Provider get lost after 30 days despite renewal fee has been paid

### ISSUE THREAD

**Issue by ronnylov** [LetheanMovement/lethean-vpn#44]
Hi!

Today I paid my monthly 10.0 LTHN renewal fee for my Lethernet FR exit node.
But it have disappeared in the Provider list in the GUI wallet.
I can still see it on nodes.lethean.io

So I tried upload sdp again

```
/opt/itns/bin/itnsdispatcher -U
WARNING:root:Uploading SDP to server https://sdp.staging.cloud.lethean.io/v1
INFO:audit:UPLOAD,SDP,/opt/itns//etc/sdp.json,
INFO:audit:NEED_PAYMENT,SDP_WALLET,wallet_address,paymentID
ERROR:root:Failed to upload service/provider config to SDP server!
ERROR:root:Error in SDP config: You have to pay for the subscription before submitting your services
ERROR:root:Error uploading SDP!
```
I experienced the same thing when Lethernet NL expired a couple of weeks ago. That time I had to create a new provider-id, pay to that and enable the exit node as new provider. After some days the old provider appeared so I had to disable that (return to old config and ipload sdp with disabled=true for the service).

I am still using lethean-vpn V3.0.0.b2 on exit node
(only wallet updated to V3.0.0.b4)

So right now my Lethernet FR is not visible in GUI wallet and I am not sure how to enable it without creating another new provider-id. Renewal functionality seems to be broken.

**Comment by ronnylov** [comment]
It is now removed from nodes.lethean.io too.
I paid before the time expired to avoid it to expire.
Now I have tried to pay again after it expired.

Here was the first transfer I did before expire:

`302521    out       2018-11-01          10.00000000 f14f980136509496650fe94cc2660eccc60f5e57b647a7ca1a86612691381ef5 befcf2ed56b474cd075fd0b5bd0747eb7708e0541326342d887784aba2dfa513     0.12847860 iz4xKrEdzsF5dP7rWaxEUT4sdaDVFbXTnD3Y9vXK5EniBFujLVp6fiAMMLEpoRno3VUccxJPnHWyRctmsPiX5Xcd3B61aDeas: 10.00000000`

And this one I did today:

` 303337    out      06:08:38 PM          10.00000000 1b1eab41cbab3b1fbf6a4aa3983df5e44806137fa223ba928bd91e591e7e9d73 befcf2ed56b474cd075fd0b5bd0747eb7708e0541326342d887784aba2dfa513     0.14538264 iz4xKrEdzsF5dP7rWaxEUT4sdaDVFbXTnD3Y9vXK5EniBFujLVp6fiAMMLEpoRno3VUccxJPnHWyRctmsPiX5Xcd3B61aDeas: 10.00000000 `


But it did not help. Not yet at least:

```
/opt/itns/bin/itnsdispatcher -U
WARNING:root:Uploading SDP to server https://sdp.staging.cloud.lethean.io/v1
INFO:audit:UPLOAD,SDP,/opt/itns//etc/sdp.json,
INFO:audit:NEED_PAYMENT,SDP_WALLET,wallet_address,paymentID
ERROR:root:Failed to upload service/provider config to SDP server!
ERROR:root:Error in SDP config: You have to pay for the subscription before submitting your services
ERROR:root:Error uploading SDP!
```

**Comment by ronnylov** [comment]
Waiting longer did not help. Still getting the same error when uploading sdp.

I have now lost my second exit node. Lethernet DE. This one I let expire without paying. Paying after expire did not enable upload of sdp again and node is not visible on nodes.lethean.io.

So the only workaround for now seems to be upload sdp with service disabled before the 30 day period expires. Then create a new provider, pay for the new provider and use that one instead of the old one. Or create a new provider after the old one expired. You loose your gained exit node rating which might be good or bad depending of previous rating.

**Comment by ronnylov** [comment]
The workaround does not work either. It is not possible to renew or make a new subscription of SDP service from version V3.0.0.b2. Maybe it is time for me to move to lethean-vpn V3.0.0.b4? I see there was a fix for sdp upload there. I totally missed that commit :-)

**Comment by alfasoftpt** [comment]
@ronnylov we are looking into this, I will provide you an update to this as soon as we have some conclusion.

**Comment by alfasoftpt** [comment]
@ronnylov can you please confirm if all your providers are showing up as usual or if you still find any missing?

**Comment by ronnylov** [comment]
I got them back except for Lethernet US because I have not paid renewal yet. I will do that and report back when payment went through.

**Comment by ronnylov** [comment]
Yes all my exit nodes are confirmed working!
We have made Lethernet great again!

**Comment by ronnylov** [comment]
Since all is fine I close it.
