### ISSUE TITLE
Add environmental variable $WALLETNAME to docker version

### ISSUE THREAD

**Issue by ronnylov** [LetheanMovement/lethean-vpn#47]
After doing some tests with docker exit node (the feature/limosek/docker branch of lethean-vpn) I have a suggestion for enhancement:

Add an environmental variable WALLETNAME to make the easy deploy script use this name instead of hardcoded "vpn" for the wallet files. You can still have the default name "vpn". Reason for this is that I use different wallet names on different exit nodes. Makes it easier to keep track of how much profit each node generate. I can just copy the wallets to my PC at home, open them and look at transactions on blockchain. It also make upgrades from old exit nodes not using docker easier. I can replace the wallet files, wallet address and wallet password using environmental variables exported to docker after replacing the files in the local etc directory.

A workaround with current version of docker exit node could be copying old wallet files and then rename them to vpn in the etc directory and use the existing environmental variables for walletpass and wallet address. I have not yet tested to do an upgrade from old non-docker to new docker.

**Comment by limosek** [comment]
Added in 74ead772b2df9f723e55b2b3a06dd5b06a327d85
WALLETFILE is relative in docker and will be stored into overlay etc dir
it is absolute path in easy-deploy-node.sh
