### ISSUE TITLE
Outdated cli wallet in lethean-vpn docker

### ISSUE THREAD

**Issue by ronnylov** [LetheanMovement/lethean-vpn#48]
I had problem getting the lethean-wallet-vpn-rpc working with latest docker image yesterday using feature/limosek/docker from dockerhub.

Looking at the code on github I noticed following in dockerfile:
`ARG DAEMON_BIN_URL="https://itns.s3.us-east-2.amazonaws.com/Cli/Cli_Ubuntu160464bitStaticRelease/1755/lethean-cli-linux-64bit-v3.0.0.b3.tar.bz2"`

I beleive this is not latest version of lethean CLI wallet and this might have caused the problem.

**Comment by ronnylov** [comment]
Use this one: https://github.com/LetheanMovement/lethean/releases/download/v3.0.0/lethean-cli-linux-64bit-v3.0.0.tar.bz2

**Comment by ronnylov** [comment]
Alse here:
`https://github.com/LetheanMovement/lethean-vpn/blob/feature/limosek/docker/server/easy-deploy-node.sh`
Default should be latest wallet version.

**Comment by limosek** [comment]
Sorry, my mistake..
Repaired in 1d7906d and 6badb60
