### ISSUE TITLE
lthnvpnc: AuthId parameter not initialized correctly

### ISSUE THREAD

**Issue by valiant1x** [LetheanMovement/lethean-vpn#73]
In haproxy client mode, passing an authID in URI format to properly initialize the local proxy.

failing:
`lthnvpnc.exe -l DEBUG connect 1b2418b6f998806c@7b08c778af3b28932185d7cc804b0cf399c05c9149613dc149dff5f30c8cd989/1b`
working:
`lthnvpnc.exe -l DEBUG connect 7b08c778af3b28932185d7cc804b0cf399c05c9149613dc149dff5f30c8cd989/1b`

It fails here:
`WARNING:lthnvpnc:Waiting for local proxy...
DEBUG:lthnvpnc:Request http://localhost:8186/stats (X-ITNS-MgmtID: None, X-ITNS-PaymentID: 1B2418B6F998806C) => 503 [Service Unavailable]`

In openVPN client mode, passing an authid in `--authid <>` param format does not actually use the specified authID. The dispatcher/client still generates its own random authID. URI mode initialization works fine.

**Comment by limosek** [comment]
Solved in https://github.com/LetheanMovement/lethean-vpn/commit/a8f9db8794ac66852065c83c7a9ab03dc60886fd#diff-77436ece1da3d12cd24138d3493c7f13
