### ISSUE TITLE
Loosing internet connection with lthnvpnc_4.exe OpenVPN after 10 minutes

### ISSUE THREAD

**Issue by ronnylov** [LetheanMovement/lethean-vpn#74]
Hi!

As mentioned in discord I am having an issue that internet browser can't load pages after 10 minutes of usage of the VPN. Attaching log files from server and client.

[lthnvpnd.log](https://github.com/LetheanMovement/lethean-vpn/files/3005346/lthnvpnd.log)
[lthnvpnc.log](https://github.com/LetheanMovement/lethean-vpn/files/3005348/lthnvpnc.log)

**Comment by valiant1x** [comment]
Hi @ronnylov, is the service time set to 10 minutes on the server side for service 1E?

This most likely relates to the more pressing bug that still exists: subsequent payments are not being processed properly for haproxy or VPN. See #75..

**Comment by ronnylov** [comment]
Time is set to 30 minutes. But there is a reneg 600 in /opt/lthn/var/vpn_1D/cfg which I bekeive might have something to do with this. Not sure though.

**Comment by ronnylov** [comment]
But thinking about it I might have run out of money because I reconnected to same authid without paying again. Well maybe the logs can give some info. The server log includes also first connection.

**Comment by valiant1x** [comment]
fixed in #81 by adding openvpn server handling of REAUTH message
