### ISSUE TITLE
Subsequent payments are not processed by dispatcher

### ISSUE THREAD

**Issue by valiant1x** [LetheanMovement/lethean-vpn#75]
Despite payments being made for service, the dispatcher is not detecting or applying subsequent payments, causing clients to be disconnected after the initial service payment period.

**Comment by limosek** [comment]
Tried to debug and find problem with second payment not processed. At least with proxy service.
But no success. I will probably need some specific SDP and specific timing. In theory, there are more sources of problem:
- payment will arrive before authid is empty in dispatcher but there is not enough confirmations.
- payment will arrive after this time. This means that authid is removed from dispatcher database and it is taken as new payment from scratch.
- payment is too small to activate next period (<minprepaidminutes)

Let us dive in and try to debug. All information is in debug.log. Please enable full debug.log and send it. Especially lines about payments and their processing/activating/deactivating

**Comment by valiant1x** [comment]
fixed in #81
